name: Publish Canary of create-vilay

on:
  push:
    branches:
      - 'main'
    paths:
      - 'packages/create/**'

jobs:
  publish-create:
    name: 'Publish create-vilay'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.2.1
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - run: pnpm install
      - run: npm pkg set version="0.0.0-$(date +%y%m%d)-${{ github.sha }}"
        working-directory: 'packages/create'
      - run: pnpm publish --no-git-checks --access public --tag canary
        working-directory: 'packages/create'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}